In [1]:
import cobra
import pandas as pd
model = cobra.io.read_sbml_model ('i_ZM4_489.xml')
cols = ['id', 'gpr', 'subunit', 'MW','notes']
df_rxns = pd.DataFrame(columns=cols)
df_rxns

Set parameter Username
Set parameter LicenseID to value 2732945
Academic license - for non-commercial use only - expires 2026-11-04

Empty DataFrame
Columns: [id, gpr, subunit, MW, notes]
Index: []

In [2]:
for rxn in model.reactions:
    if rxn.subsystem and 'biomass' in rxn.subsystem.lower() and rxn.id != 'PEPTIDOr_ZM':
        continue
    if rxn.id[:3] == 'EX_':
        i = 'RXN-' + rxn.id + '-SPONT'
        df_rxns.loc[i, 'id'] = i
        df_rxns.loc[i, 'gpr'] = 'SPONT'
        continue
    genes = [g.id for g in rxn.genes]
    if len(genes) == 0:
        i = 'RXN-' + rxn.id + '-UNKNOWN'
        df_rxns.loc[i, 'id'] = i
        df_rxns.loc[i, 'gpr'] = 'UNKNOWN'

    else:
        gpr = rxn.gene_reaction_rule
    # If not composed of different subunits
        if ' and ' not in gpr:
            for g in genes:
                if g == 'UNKNOWN':
                    i = 'RXN-' + rxn.id + '-UNKNOWN'
                    df_rxns.loc[i, 'id'] = i
                    df_rxns.loc[i, 'gpr'] = 'UNKNOWN'
                elif g in ['TRUE', 'SPONT']:
                    i = 'RXN-' + rxn.id + '-SPONT'
                    df_rxns.loc[i, 'id'] = i
                    df_rxns.loc[i, 'gpr'] = 'SPONT'
                else:
                    i = 'RXN-' + rxn.id + '-' + g
                    df_rxns.loc[i, 'id'] = i
                    df_rxns.loc[i, 'gpr'] = g
        # If composed of subunits
        else:
            i = 'RXN-' + rxn.id
            df_rxns.loc[i, 'id'] = i
            df_rxns.loc[i, 'gpr'] = rxn.gene_reaction_rule
            df_rxns.loc[i, 'notes'] = 'manualBuildSubunit'

In [3]:
df_rxns

                                        id      gpr subunit   MW notes
RXN-EX_3dhq_e-SPONT    RXN-EX_3dhq_e-SPONT    SPONT     NaN  NaN   NaN
RXN-EX_3dhsk_e-SPONT  RXN-EX_3dhsk_e-SPONT    SPONT     NaN  NaN   NaN
RXN-EX_4hbz_e-SPONT    RXN-EX_4hbz_e-SPONT    SPONT     NaN  NaN   NaN
RXN-EX_ac_e-SPONT        RXN-EX_ac_e-SPONT    SPONT     NaN  NaN   NaN
RXN-EX_acald_e-SPONT  RXN-EX_acald_e-SPONT    SPONT     NaN  NaN   NaN
...                                    ...      ...     ...  ...   ...
RXN-GLNTRS-ZMO0783      RXN-GLNTRS-ZMO0783  ZMO0783     NaN  NaN   NaN
RXN-GLNTRS-ZMO0784      RXN-GLNTRS-ZMO0784  ZMO0784     NaN  NaN   NaN
RXN-RIBDH-ZMO0353        RXN-RIBDH-ZMO0353  ZMO0353     NaN  NaN   NaN
RXN-RIBCT-ZMO0353        RXN-RIBCT-ZMO0353  ZMO0353     NaN  NaN   NaN
RXN-PCS-UNKNOWN            RXN-PCS-UNKNOWN  UNKNOWN     NaN  NaN   NaN

[921 rows x 5 columns]

In [4]:
df_rxns.to_excel('metabolic_reactions.xlsx',index=None)

In [5]:
# This file should be manually curated into enzyme complexes for the multiple genes, and/or in GRP
df = df_rxns[df_rxns.notes.isnull() == False]
df.to_excel('metabolic_reactions_RequireCuration_ZM.xlsx', index=None)

In [6]:
df_cure = pd.read_excel('metabolic_reactions_ManualCuration_ZM.xlsx',sheet_name = 'Step2')
df_cure

,id,gpr,enz,subunit,MW,notes
0,RXN-SADT2,ZMO0004 and ZMO0005,ZMOenz1,NaN,NaN,manualBuildSubunit
1,RXN-PAPSR2,ZMO0007 and ZMO0573,ZMOenz2,NaN,NaN,NaN
2,RXN-PAPSR2,ZMO0007 and ZMO0753,ZMOenz3,NaN,NaN,manualBuildSubunit
3,RXN-PAPSR,ZMO0007 and ZMO1097,ZMOenz4,NaN,NaN,manualBuildSubunit
4,RXN-PAPSR2,ZMO0007 and ZMO1873,ZMOenz5,NaN,NaN,NaN
...,...,...,...,...,...,...
72,RXN-CBPS,ZMO1618 and ZMO1617,ZMOenz43,NaN,NaN,manualBuildSubunit
73,RXN-RNFfld,ZMO1814 and ZMO1813 and ZMO1812 and ZMO1811 an...,ZMOenz44,NaN,NaN,manualBuildSubunit
74,RXN-RNFfdx,ZMO1814 and ZMO1813 and ZMO1812 and ZMO1811 an...,ZMOenz44,NaN,NaN,manualBuildSubunit
75,RXN-NIT1b_fld,ZMO1823 and ZMO1824 and ZMO1825,ZMOenz45,NaN,NaN,manualBuildSubunit
76,RXN-NIT1b_fdx,ZMO1823 and ZMO1824 and ZMO1825,ZMOenz45,NaN,NaN,manualBuildSubunit

In [7]:
# metabolic reactions without the manual required rxn2enz (62reactions)(937-62=875)
df_rxns2 = df_rxns.copy()
df_rxns2 = df_rxns2[df_rxns2.notes.isnull()]
df_rxns2

                                        id      gpr subunit   MW notes
RXN-EX_3dhq_e-SPONT    RXN-EX_3dhq_e-SPONT    SPONT     NaN  NaN   NaN
RXN-EX_3dhsk_e-SPONT  RXN-EX_3dhsk_e-SPONT    SPONT     NaN  NaN   NaN
RXN-EX_4hbz_e-SPONT    RXN-EX_4hbz_e-SPONT    SPONT     NaN  NaN   NaN
RXN-EX_ac_e-SPONT        RXN-EX_ac_e-SPONT    SPONT     NaN  NaN   NaN
RXN-EX_acald_e-SPONT  RXN-EX_acald_e-SPONT    SPONT     NaN  NaN   NaN
...                                    ...      ...     ...  ...   ...
RXN-GLNTRS-ZMO0783      RXN-GLNTRS-ZMO0783  ZMO0783     NaN  NaN   NaN
RXN-GLNTRS-ZMO0784      RXN-GLNTRS-ZMO0784  ZMO0784     NaN  NaN   NaN
RXN-RIBDH-ZMO0353        RXN-RIBDH-ZMO0353  ZMO0353     NaN  NaN   NaN
RXN-RIBCT-ZMO0353        RXN-RIBCT-ZMO0353  ZMO0353     NaN  NaN   NaN
RXN-PCS-UNKNOWN            RXN-PCS-UNKNOWN  UNKNOWN     NaN  NaN   NaN

[856 rows x 5 columns]

In [8]:
if 'enz' not in df_rxns2.columns:
    df_rxns2.insert(2, 'enz', df_rxns2.gpr)

In [9]:
df_rxns2

,id,gpr,enz,subunit,MW,notes
RXN-EX_3dhq_e-SPONT,RXN-EX_3dhq_e-SPONT,SPONT,SPONT,NaN,NaN,NaN
RXN-EX_3dhsk_e-SPONT,RXN-EX_3dhsk_e-SPONT,SPONT,SPONT,NaN,NaN,NaN
RXN-EX_4hbz_e-SPONT,RXN-EX_4hbz_e-SPONT,SPONT,SPONT,NaN,NaN,NaN
RXN-EX_ac_e-SPONT,RXN-EX_ac_e-SPONT,SPONT,SPONT,NaN,NaN,NaN
RXN-EX_acald_e-SPONT,RXN-EX_acald_e-SPONT,SPONT,SPONT,NaN,NaN,NaN
...,...,...,...,...,...,...
RXN-GLNTRS-ZMO0783,RXN-GLNTRS-ZMO0783,ZMO0783,ZMO0783,NaN,NaN,NaN
RXN-GLNTRS-ZMO0784,RXN-GLNTRS-ZMO0784,ZMO0784,ZMO0784,NaN,NaN,NaN
RXN-RIBDH-ZMO0353,RXN-RIBDH-ZMO0353,ZMO0353,ZMO0353,NaN,NaN,NaN
RXN-RIBCT-ZMO0353,RXN-RIBCT-ZMO0353,ZMO0353,ZMO0353,NaN,NaN,NaN
RXN-PCS-UNKNOWN,RXN-PCS-UNKNOWN,UNKNOWN,UNKNOWN,NaN,NaN,NaN

In [10]:
cols = ['gpr', 'enz', 'subunit','MW', 'notes']
for i in df_cure.index:
    rxn = df_cure.id[i] + '-' + df_cure.enz[i]
    df_rxns2.loc[rxn, 'id'] = rxn
    df_rxns2.loc[rxn, cols] = df_cure.loc[i, cols]

In [11]:
df_rxns2

,id,gpr,enz,subunit,MW,notes
RXN-EX_3dhq_e-SPONT,RXN-EX_3dhq_e-SPONT,SPONT,SPONT,NaN,NaN,NaN
RXN-EX_3dhsk_e-SPONT,RXN-EX_3dhsk_e-SPONT,SPONT,SPONT,NaN,NaN,NaN
RXN-EX_4hbz_e-SPONT,RXN-EX_4hbz_e-SPONT,SPONT,SPONT,NaN,NaN,NaN
RXN-EX_ac_e-SPONT,RXN-EX_ac_e-SPONT,SPONT,SPONT,NaN,NaN,NaN
RXN-EX_acald_e-SPONT,RXN-EX_acald_e-SPONT,SPONT,SPONT,NaN,NaN,NaN
...,...,...,...,...,...,...
RXN-CBPS-ZMOenz43,RXN-CBPS-ZMOenz43,ZMO1618 and ZMO1617,ZMOenz43,NaN,NaN,manualBuildSubunit
RXN-RNFfld-ZMOenz44,RXN-RNFfld-ZMOenz44,ZMO1814 and ZMO1813 and ZMO1812 and ZMO1811 an...,ZMOenz44,NaN,NaN,manualBuildSubunit
RXN-RNFfdx-ZMOenz44,RXN-RNFfdx-ZMOenz44,ZMO1814 and ZMO1813 and ZMO1812 and ZMO1811 an...,ZMOenz44,NaN,NaN,manualBuildSubunit
RXN-NIT1b_fld-ZMOenz45,RXN-NIT1b_fld-ZMOenz45,ZMO1823 and ZMO1824 and ZMO1825,ZMOenz45,NaN,NaN,manualBuildSubunit
RXN-NIT1b_fdx-ZMOenz45,RXN-NIT1b_fdx-ZMOenz45,ZMO1823 and ZMO1824 and ZMO1825,ZMOenz45,NaN,NaN,manualBuildSubunit

In [12]:
cols = ['id', 'rxn_src', 'enz', 'gpr']
df_rxns3 = pd.DataFrame(columns=cols)

rxns_model = [rxn.id for rxn in model.reactions]

for i in df_rxns2.index:
    entry = df_rxns2.id[i]
    header = entry.split('-')[0]
    rxnid = entry.split('-')[1]
    gid = entry[len(header)+len(rxnid)+2:]
    
    if rxnid not in rxns_model:
        continue
    
    rxn = model.reactions.get_by_id(rxnid)
    if rxn.upper_bound > 0:
        enew = 'RXN-' + rxnid + '_FWD' + '-' + gid
        df_rxns3.loc[enew, 'id'] = enew
        df_rxns3.loc[enew, 'rxn_src'] = rxn.id
        df_rxns3.loc[enew, 'enz'] = df_rxns2.enz[i]
        df_rxns3.loc[enew, 'gpr'] = df_rxns2.gpr[i]
    if rxn.lower_bound < 0:
        enew = 'RXN-' + rxnid + '_REV' + '-' + gid
        df_rxns3.loc[enew, 'id'] = enew
        df_rxns3.loc[enew, 'rxn_src'] = rxn.id
        df_rxns3.loc[enew, 'enz'] = df_rxns2.enz[i]
        df_rxns3.loc[enew, 'gpr'] = df_rxns2.gpr[i]

In [13]:
df_rxns3

,id,rxn_src,enz,gpr
RXN-EX_3dhq_e_FWD-SPONT,RXN-EX_3dhq_e_FWD-SPONT,EX_3dhq_e,SPONT,SPONT
RXN-EX_3dhsk_e_FWD-SPONT,RXN-EX_3dhsk_e_FWD-SPONT,EX_3dhsk_e,SPONT,SPONT
RXN-EX_4hbz_e_FWD-SPONT,RXN-EX_4hbz_e_FWD-SPONT,EX_4hbz_e,SPONT,SPONT
RXN-EX_ac_e_FWD-SPONT,RXN-EX_ac_e_FWD-SPONT,EX_ac_e,SPONT,SPONT
RXN-EX_acald_e_FWD-SPONT,RXN-EX_acald_e_FWD-SPONT,EX_acald_e,SPONT,SPONT
...,...,...,...,...
RXN-RNFfdx_REV-ZMOenz44,RXN-RNFfdx_REV-ZMOenz44,RNFfdx,ZMOenz44,ZMO1814 and ZMO1813 and ZMO1812 and ZMO1811 an...
RXN-NIT1b_fld_FWD-ZMOenz45,RXN-NIT1b_fld_FWD-ZMOenz45,NIT1b_fld,ZMOenz45,ZMO1823 and ZMO1824 and ZMO1825
RXN-NIT1b_fld_REV-ZMOenz45,RXN-NIT1b_fld_REV-ZMOenz45,NIT1b_fld,ZMOenz45,ZMO1823 and ZMO1824 and ZMO1825
RXN-NIT1b_fdx_FWD-ZMOenz45,RXN-NIT1b_fdx_FWD-ZMOenz45,NIT1b_fdx,ZMOenz45,ZMO1823 and ZMO1824 and ZMO1825
RXN-NIT1b_fdx_REV-ZMOenz45,RXN-NIT1b_fdx_REV-ZMOenz45,NIT1b_fdx,ZMOenz45,ZMO1823 and ZMO1824 and ZMO1825

In [14]:
df_rxns3.to_excel('rxns_enz_ZM_v3.xlsx', index=False)

In [15]:
cols = ['id', 'rxn_src', 'enz', 'gpr','MW','subunit']
df_rxns4 = pd.DataFrame(columns=cols)

In [16]:
df_enz = pd.read_excel('rxns_enz_ZM_v3.xlsx')
df_enz.index = df_enz.gpr.to_list()
df_enz.index
#change enz to gpr (since some of enz has multiple genes)

Index(['SPONT', 'SPONT', 'SPONT', 'SPONT', 'SPONT', 'SPONT', 'SPONT', 'SPONT',
       'SPONT', 'SPONT',
       ...
       'ZMO1605 and ZMO1606 and ZMO0510 and ZMO0512', 'ZMO1618 and ZMO1617',
       'ZMO1814 and ZMO1813 and ZMO1812 and ZMO1811 and ZMO1810 and ZMO1809 and ZMO1808',
       'ZMO1814 and ZMO1813 and ZMO1812 and ZMO1811 and ZMO1810 and ZMO1809 and ZMO1808',
       'ZMO1814 and ZMO1813 and ZMO1812 and ZMO1811 and ZMO1810 and ZMO1809 and ZMO1808',
       'ZMO1814 and ZMO1813 and ZMO1812 and ZMO1811 and ZMO1810 and ZMO1809 and ZMO1808',
       'ZMO1823 and ZMO1824 and ZMO1825', 'ZMO1823 and ZMO1824 and ZMO1825',
       'ZMO1823 and ZMO1824 and ZMO1825', 'ZMO1823 and ZMO1824 and ZMO1825'],
      dtype='object', length=1209)

In [17]:
df_pro = pd.read_excel('enz_info_uniprot.xlsx')
df_pro.index = df_pro.id.to_list()
df_pro.index

Index(['ZMO0374', 'ZMO0363', 'ZMO0420', 'ZMO1150', 'ZMO1180', 'ZMO1618',
       'ZMO1617', 'ZMO1360', 'ZMO1596', 'ZMO1608',
       ...
             nan,       nan,       nan,       nan,       nan,       nan,
             nan, 'ZMO1566', 'ZMO0842', 'ZMO1353'],
      dtype='object', length=1779)

In [18]:
# Check again this step
for i in df_enz.index:
    for j in df_pro.index:
        if i == j:
            genes = i
            df_rxns4.loc[genes,'id'] = i
            #df_rxns4.loc[genes,'enz'] = df_enz.enz[i]
            #df_rxns4.loc[genes,'rxn_src'] = df_enz.src[i]
            #df_rxns4.loc[genes,'gpr'] = df_enz.gpr[i]
            df_rxns4.loc[genes,'MW'] = df_pro.Mass[j]
            df_rxns4.loc[genes,'subunit']=df_pro.Subunit[j]

In [19]:
df_rxns4

,id,rxn_src,enz,gpr,MW,subunit
ZMO1284,ZMO1284,NaN,NaN,NaN,52288,NaN
ZMO0788,ZMO0788,NaN,NaN,NaN,54701,NaN
ZMO1146,ZMO1146,NaN,NaN,NaN,17271,NaN
ZMO1222,ZMO1222,NaN,NaN,NaN,25695,SUBUNIT: Homotetramer. {ECO:0000256|RuleBase:R...
ZMO1278,ZMO1278,NaN,NaN,NaN,44340,NaN
...,...,...,...,...,...,...
ZMO0873,ZMO0873,NaN,NaN,NaN,23998,NaN
ZMO0782,ZMO0782,NaN,NaN,NaN,54110,"SUBUNIT: Heterotrimer of A, B and C subunits. ..."
ZMO0784,ZMO0784,NaN,NaN,NaN,10357,"SUBUNIT: Heterotrimer of A, B and C subunits. ..."
ZMO0783,ZMO0783,NaN,NaN,NaN,52343,"SUBUNIT: Heterotrimer of A, B and C subunits. ..."
ZMO0353,ZMO0353,NaN,NaN,NaN,48389,NaN

In [20]:
for i in df_enz.gpr:
    for j in df_pro.id:
        if i == j:
            genes = i
            df_enz.loc[genes,'subunit']=df_pro.Subunit[j]

/var/folders/ff/d_g5y_gd46b0d_46c3rqlvth0000gn/T/ipykernel_83008/77803416.py:5: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'SUBUNIT: Homotetramer. {ECO:0000256|RuleBase:RU366074}.' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df_enz.loc[genes,'subunit']=df_pro.Subunit[j]

In [21]:
df_enz.insert(5, 'MW', '')
df_enz

,id,rxn_src,enz,gpr,subunit,MW
SPONT,RXN-EX_3dhq_e_FWD-SPONT,EX_3dhq_e,SPONT,SPONT,NaN,
SPONT,RXN-EX_3dhsk_e_FWD-SPONT,EX_3dhsk_e,SPONT,SPONT,NaN,
SPONT,RXN-EX_4hbz_e_FWD-SPONT,EX_4hbz_e,SPONT,SPONT,NaN,
SPONT,RXN-EX_ac_e_FWD-SPONT,EX_ac_e,SPONT,SPONT,NaN,
SPONT,RXN-EX_acald_e_FWD-SPONT,EX_acald_e,SPONT,SPONT,NaN,
...,...,...,...,...,...,...
ZMO1814 and ZMO1813 and ZMO1812 and ZMO1811 and ZMO1810 and ZMO1809 and ZMO1808,RXN-RNFfdx_REV-ZMOenz44,RNFfdx,ZMOenz44,ZMO1814 and ZMO1813 and ZMO1812 and ZMO1811 an...,NaN,
ZMO1823 and ZMO1824 and ZMO1825,RXN-NIT1b_fld_FWD-ZMOenz45,NIT1b_fld,ZMOenz45,ZMO1823 and ZMO1824 and ZMO1825,NaN,
ZMO1823 and ZMO1824 and ZMO1825,RXN-NIT1b_fld_REV-ZMOenz45,NIT1b_fld,ZMOenz45,ZMO1823 and ZMO1824 and ZMO1825,NaN,
ZMO1823 and ZMO1824 and ZMO1825,RXN-NIT1b_fdx_FWD-ZMOenz45,NIT1b_fdx,ZMOenz45,ZMO1823 and ZMO1824 and ZMO1825,NaN,
ZMO1823 and ZMO1824 and ZMO1825,RXN-NIT1b_fdx_REV-ZMOenz45,NIT1b_fdx,ZMOenz45,ZMO1823 and ZMO1824 and ZMO1825,NaN,

In [22]:
for i in df_enz.gpr:
    for j in df_pro.id:
        if i == j:
            genes = i
            df_enz.loc[genes,'MW']=df_pro.Mass[j]

In [23]:
df_enz
df_enz.to_excel('Enzyme_ZM.xlsx',index=False)